version: "3.3"  # compatible avec Cloud Shell
services:
  app:
    build: ./docker/apache
    container_name: codeigniter_app
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
      - python

  db:
    image: mysql:8.0
    container_name: codeigniter_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codeigniter
      MYSQL_USER: ci_user
      MYSQL_PASSWORD: ci_pass
    volumes:
      - db_data:/var/lib/mysql

  python:
    build: ./python
    container_name: flask_ai
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "5000:5000"

volumes:
  db_data:
